#+TITLE: Vagrant Mesos (2 master/2 slave setup)

* Introduction

This follows the installation instructions for a multi-node mesos
setup [[https://docs.google.com/document/d/1rO7bg0uQH5uzxzRoq0gNdvubpWNA5XIkdGiwhyeh9wo/edit][(Installation Instructions]]).

The current view is two masters and two slaves (which will required
approx 10Gb of RAM for the install to succeed. It will also required a
fair amount of disk space). The number of masters and slaves can be
easily extended using the pattern outlines in the /Vagrantfile/, but
system resorces will need to be available.

Virtual Machines will be created with private space IP numbers:

- masters :: 192.168.0.10, 192.168.0.11, and, 

- slaves :: 192.168.0.5 and 192.168.0.6. 

If these aren't appropriate then the Vagrantfile and config-files will
have to be updated.

*Note:* This is simply to experiment with the tools (and to document
the setup a little further).

* Setup Instructions
This will require two components to be installed:

- VirtualBox - 5.0.6 (https://www.virtualbox.org)
- Vagrant - 1.7.4 (https://www.vagrantup.com/)

There is also a need for a command-line tool such as bash, shell, etc
and that the paths are set correctly for 'vagrant' to be
executable. These are the latest versions which have been tested
(prior versions will not be tested). On Windows, [[www.cygwin.org][cygwin]] could be
installed which will provide bash along with an assortment of other
GNU open-source tools.

* Building of the VMs
The following steps should be sufficient:

- *cd <Clone Directory>*
- *vagrant up* which will build the virtual machine (will take a while
  depending on environment/network speed).

  Note: This first time the VM is created, it is *required* to do a restart
  from scratch (rebooting will finalise some network setup).

  - *vagrant halt*
  - *vagrant up*

Then it should be possible to login to the machine(s) using:

- *vagrant ssh slave1* 

* Mesos Testing

Accessing http://192.168.0.10:5050/ should show 2 actives slaves (shutting
down a slave will leave to it becoming deactivated, etc.)

** Basic Tests
- Start the system, access the link and check that 2 slaves are visible
- Shut down one of the slaves (and watch it pass from deactivated to gone)
- Restart the slave and check it becomes active again.
- power down the master and check the other master continues

* Start Hadoop services

Hadoop services are not yet started on boot. So the following will have to be 
executed as hduser.

#+BEGIN_QUOTE:
start-dfs.sh
start-yarn.sh
jps
#+END_QUOTE

