#+TITLE: Vagrant (Multiple Node Setup)

* Introduction

This follows the installation instructions for a multi-node mesos
setup[1].  The current view is two masters and two slaves (which will
required 10Gb of RAM to be installed, with a fair amount of disk
space).

* Setup Instructions

This will require two components to be installed:
- VirtualBox - 
- Vagrant - https://www.vagrantup.com/

The following steps sjould be sufficient:

- *cd <Clone Directory>*
- *vagrant up* which will build the virtual machine (will take a while
  depending on environment/network speed).

  Note: This first time the VM is created, it is best to do a restart
  from scratch (reboot can be requird to finalise some installs).
  - *vagrant halt*
  - *vagrant up*

Then it should be possible to login to the vagrant machine try the 
examples.

* Mesos Testing

Accessing http://192.168.0.10:5050/ should show 2 actives slaves (shutting
down a slave will leave to it becoming deactivated, etc.)

* Start Hadoop services

Hadoop services are not yet started on boot. So the following will have to be 
executed as hduser.

#+BEGIN_QUOTE:
start-dfs.sh
start-yarn.sh
jps
#+END_QUOTE

* Run Examples

hadoop jar /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.1.jar pi 2 5

* Pointers

[1] https://docs.google.com/document/d/1rO7bg0uQH5uzxzRoq0gNdvubpWNA5XIkdGiwhyeh9wo/edit
